### ISSUE TITLE
cc vs ccc (both have state)

### ISSUE THREAD

**Issue by elijahmanor** [burkeholland/simple-react-snippets#12]
I noticed that both `cc` and `ccc` have state defined in them, but using different techniques (static property vs constructor). 

Was adding state to `cc` intentional? The reason I ask is the trigger for `ccc` says "Class Component With State" so I was guessing `cc` was without state.

Was that intentional?

**Comment by elijahmanor** [comment]
Never-mind, I see the issue. There is just a text mismatch.

In the README.md table `ccc` says "Class Component With Constructor", but further down with the snippet code it says "ccc - Class Component With State"

I'll make a PR to update

**Comment by burkeholland** [comment]
Fixed in #13
