### ISSUE TITLE
Update setState snippet

### ISSUE THREAD

**Issue by ajayns** [burkeholland/simple-react-snippets#17]
Currently the `setState` expansion is pretty small and doesn't include `prevState`.

I'd say it'd be a great idea to either add that as a new snippet or improve on the current `ss` shortcut.

The new expansion will be: 
```javascript
  this.setState(prevState => { 
    return { | :  }
  })
```

**Comment by blurbyte** [comment]
Already done it in #16. Hopefully it will get merged soon :)

**Comment by burkeholland** [comment]
Merged!
