### ISSUE TITLE
I badly need NO semicolons

### ISSUE THREAD

**Issue by pawelotto** [burkeholland/simple-react-snippets#20]
How do I **NOT** insert semicolons at the line end with your snippets?

**Comment by rbtprograms** [comment]
Download one of the other react snippets on VSCode, plenty of them do not use semi colons.

**Comment by Stas-Buzunko** [comment]
had to delete because of this

**Comment by burkeholland** [comment]
Isn't this something that Prettier should handle? Should we default to no semicolons and let Prettier add them back?

**Comment by apicgg** [comment]
> Isn't this something that Prettier should handle? Should we default to no semicolons and let Prettier add them back?

It will be better if it is handled by Prettier.
