### ISSUE TITLE
Feature Request: Function Components

### ISSUE THREAD

**Issue by dons20** [burkeholland/simple-react-snippets#26]
Class components are fine but it would be nice to have a function component snippet seeing that [both class and function components are valid](https://reactjs.org/docs/components-and-props.html). If needed I could do a PR if this is something you don't have time for.

**Comment by deadcoder0904** [comment]
@burkeholland can we get this? Especially since Hooks are released now :)

**Comment by burkeholland** [comment]
I think this is resolved with the Function Syntax Component `ffc`...

```json
"Function Syntax Component": {
    "prefix": "ffc",
    "body": [
      "function $1($2) {",
      "\treturn ( $0 );",
      "}",
      "",
      "export default $1;"
    ],
    "description": "Function Syntax Component"
  },
```
