### ISSUE TITLE
Snippets just show up once then disappear

### ISSUE THREAD

**Issue by Dalesttn** [burkeholland/simple-react-snippets#35]
So the snippets only show once after each start of vscode, im using jsx extension and here is my vscode install 

Version: 1.41.1 (system setup)
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by burkeholland** [comment]
I'm not able to reproduce. Is this still an issue for you?
