### ISSUE TITLE
Snippets not showing up

### ISSUE THREAD

**Issue by michaelaflores** [burkeholland/simple-react-snippets#5]
I've installed the extension but the listed snippet shortcuts don't show up in files associated with JavaScript React. Here's my file associations from my user settings:
`    "files.associations": {
      "*.vue": "html",
      "*.js": "javascriptreact"
    }
`
I thought maybe it needed to be associated instead with plain JavaScript but that wasn't the case. Any ideas?

**Comment by rkpatel33** [comment]
+1 Same issue. I just clicked `install`, made no changes to my settings, and snippets don't show up in `*.jsx` files. Any suggestions here on debugging?

![image](https://user-images.githubusercontent.com/3799489/31560943-2549a63c-b00b-11e7-9d2e-c6648d1ddf96.png)

**Comment by wKovacs64** [comment]
I'm noticing it works sporadically. If I bring up the Command Palette (Ctrl-Shift-P) and use the `Insert Snippet` option, I can reliably find them there. They just don't always work in shortcut form. If I reload the window, they start working again - haven't tracked down what causes them to stop, though.

**Comment by burkeholland** [comment]
I think this was because I didn't have the configuration right to support both .jsx AND regular .js. New version (1.0.7) is live in the extension gallery with a fix. Please update and let me know if it fixes your issue.

**Comment by rkpatel33** [comment]
Seems like this is working now, thanks!


_________________________
Rishi Patel | mail@rishinyc.com

**Comment by landed1** [comment]
I am finding mine is only working for .js types. My version is 1.2.3

**Comment by SaifuddinSaifee** [comment]
Hey Bruke! I m still facing this issue. I m currently on version 1.2.7
![image](https://user-images.githubusercontent.com/18860009/216916110-e93bbbd9-700e-40b9-8feb-af32fce10a9a.png)

Here's my file associations from my user settings:
![image](https://user-images.githubusercontent.com/18860009/216916694-93e922fa-41f2-40ec-9da5-990265e36f5a.png)

Let me know how I may resolve this, Thanks!

**Comment by Dotolox** [comment]
I have the excat same problem with the exact same Include Languages Settings. I worked fine until today.

**Comment by giorgio-villani** [comment]
adding "-" in front of scf allows for the intellisense to popup. not sure why this is happening. i'm thinking it could be interference from another extension

**Comment by pixelfast** [comment]
I did this and it fixed it.
![image](https://user-images.githubusercontent.com/22091415/217682314-e02238ed-a43f-4e11-8046-dcf71ee254dd.png)

**Comment by nihal1512** [comment]
![image](https://github.com/burkeholland/simple-react-snippets/assets/78658399/d1f34fe4-2bd7-43e8-923a-c7709044cdaa)

Snippets not working

**Comment by cvogitgud** [comment]
I was running into this issue when I realized I just didn't have VS Code configured to show Snippet suggestions in the editor, so check that you have that enabled!

Settings -> Editor: Snippet suggestions (from none to whatever you prefer)

**Comment by jordanaf808** [comment]
> Removing the "javascript" : "javascriptreact" mapping completely from user settings FIXED it for me. Not sure why.

Same for me, I wasn't able to see snippet suggestions before making this change, but now my Emmet suggestions don't work anymore in jsx files.
