### ISSUE TITLE
Enable simple react snippets extension to run on VS Code on the web

### ISSUE THREAD

**Issue by isidorn** [burkeholland/simple-react-snippets#68]
Hey @burkeholland,

Let's try to enable this extension for the web. Might you have time to look into this?
This guide is great https://code.visualstudio.com/api/extension-guides/web-extensions
As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

I think you just need to add a `browser` entry point in your `package.json`. Do you have some node dependencies?

**Comment by burkeholland** [comment]
Hey Isa!

Added the entry point for browser. There is only one source file so I don’t think webpack is needed here. On vacation at the moment with only an iPad and the `vsce login` wants an x11 display. Will publish when I return this weekend.

**Comment by burkeholland** [comment]
Fixed in 2d5e604

**Comment by isidorn** [comment]
Awesome thanks a lot Burke! Once you publish I can verify all is working as expected.

**Comment by burkeholland** [comment]
Published and verified that it works. Thank you for the directions!
