### ISSUE TITLE
Feature request: HOC snippet

### ISSUE THREAD

**Issue by will-stone** [burkeholland/simple-react-snippets#7]
It would be great to have a snippet for creating a [HOC](https://reactjs.org/docs/higher-order-components.html). I'll look into sending you a pull request if I get the time.

**Comment by burkeholland** [comment]
Would love this contribution!

**Comment by burkeholland** [comment]
What do you think of this format?

```js
function withSubscription(WrappedComponent) {
  return class extends Component {
    constructor(props) {
      super(props);
    }
 
    render() {
      return <WrappedComponent {...this.props} />;
    }
  }
}
```

Here is what it looks like in action...

![hoc snippet in action](https://i.imgur.com/Dyfv2aA.gif)

**Comment by will-stone** [comment]
This is great. Thanks!
