### ISSUE TITLE
sfc not found

### ISSUE THREAD

**Issue by heidgert** [burkeholland/simple-react-snippets#74]
I have just installed version 1.2.4 of Simple React Snippets but `sfc` is not being found when I type:

![image](https://user-images.githubusercontent.com/9531120/162159912-42a3a869-0d3c-4455-8d85-168aa3a9e234.png)

Other snippets seems to be working, such as `ffc` as can be seen below:

![image](https://user-images.githubusercontent.com/9531120/162160346-0a69dac2-3c83-4c39-bfae-7230400e401c.png)

**Comment by imar-io** [comment]
Have the issue (v1.2.6)

**Comment by florianwalther-private** [comment]
Same issue here. I always create my files as `.jsx` files first, use the template, and then rename it to `.tsx`.

**Comment by JLucasCAmorim** [comment]
Same here, Any updates about it? @burkeholland

**Comment by dytra** [comment]
i have the same issue here

**Comment by rbaguila** [comment]
same issue here

**Comment by PsyChonek** [comment]
+1

**Comment by moraesvic** [comment]
+1

**Comment by moraesvic** [comment]
[Pull Request #77](https://github.com/burkeholland/simple-react-snippets/pull/77) submitted addressing this issue

**Comment by Zicio** [comment]
+1

**Comment by EmilieHB** [comment]
+1

**Comment by stijnelskens** [comment]
+1
