### ISSUE TITLE
[Feature Request] Add option create function components with export default inline

### ISSUE THREAD

**Issue by iamshaheenumar** [burkeholland/simple-react-snippets#88]
Hello,
Wanted to request  a snippet for Function Component with export default.

Example:

![image](https://github.com/burkeholland/simple-react-snippets/assets/24774809/c9a10b77-b085-4898-b1a6-a6cbb71a5fea)

I know we already have `ffc` for Function Component, but some people prefer to write export default inline.
I suggest to add a new snippet `efc` or `effc` for this scenario.

By the way, thank you for this great extension 👍 😃

**Comment by konrad-bak** [comment]
Why not just change the snippet to inline export default?
Or even better - give this extension a setting to choose "inline export default"/"export default at the bottom of file"

adding extra `effc` will add unnessesary confusion/complicity when every user will only use one or another
